/* tslint:disable */
/* eslint-disable */
/**
* (Generated by WASM.)
* @param {string} s
* @returns {any}
*/
export function parse(s: string): any;
/**
* Format a JS file.
* @param {any} js_file
* @returns {string}
*/
export function format_from_js_file(js_file: any): string;
/**
* wasm version of the flux_find_var_type() API. Instead of returning a flat buffer that contains
* the MonoType, it returns a JsValue。
* @param {string} source
* @param {string} file_name
* @param {string} var_name
* @returns {any}
*/
export function wasm_find_var_type(source: string, file_name: string, var_name: string): any;
/**
* Gets json docs from a Flux identifier
* @param {string} flux_path
* @returns {any}
*/
export function get_json_documentation(flux_path: string): any;
